// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: nmea2000_wind_mfd

#include "ui.h"
#include "ui_helpers.h"
#include "Arduino.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Screen1_Image1;
lv_obj_t *ui_Screen1_Image2;
lv_obj_t *ui_lbOilPRessure_value;
lv_obj_t *ui_Screen1_LabelpsiUnits;
lv_obj_t *ui_Screen1_LabelOilPressure;
lv_obj_t *ui_lbFuelFlow;
lv_obj_t *ui_lbFuelBurned_Value;
lv_obj_t *ui_Screen1_LabelFuelFlow;
lv_obj_t *ui_Screen1_Label9;
lv_obj_t *ui_Screen1_LabelGPH;
lv_obj_t *ui_Screen1_LabelGallons;
lv_obj_t *ui_lbEngineRPM_value;
lv_obj_t *ui_lbAltVolt;
lv_obj_t *ui_Screen1_LabelRPM;
lv_obj_t *ui_Screen1_LabelVolt_Units;
lv_obj_t *ui_Screen1_LabelVoltage;
lv_obj_t *ui_Screen1_LabelEngineSpeed;

//SCREEN: ui_ScreenSplash
void ui_ScreenSplash_screen_init(void);
lv_obj_t *ui_ScreenSplash;
lv_obj_t *ui_ScreenSplash_Image1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);

lv_timer_set_repeat_count(lv_timer_create(endSplash, 8000, NULL), 1);
ui_ScreenSplash_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenSplash);
}

void endSplash(lv_timer_t * timer)
{
    LV_LOG("splash ended");
    ui_Screen1_screen_init();
    lv_disp_load_scr( ui_Screen1);
    lv_obj_del( ui_ScreenSplash);
}