// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: nmea2000_wind_mfd

#include "ui.h"
#include "ui_helpers.h"
#include "Arduino.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Screen1_Image1;
lv_obj_t *ui_Screen1_Image2;
lv_obj_t *ui_lbWindDirection;
lv_obj_t *ui_lbWindSpeed;
lv_obj_t *ui_Screen1_Label3;
lv_obj_t *ui_Screen1_Label1;
lv_obj_t *ui_Screen1_Label4;
lv_obj_t *ui_Screen1_Label5;
lv_obj_t *ui_Screen1_Label2;
lv_obj_t *ui_lbWaterTemp;
lv_obj_t *ui_Screen1_Label6;
lv_obj_t *ui_Screen1_Label7;
lv_obj_t *ui_lbFuelFlow;
lv_obj_t *ui_lbFuelBurned;
lv_obj_t *ui_Screen1_Label8;
lv_obj_t *ui_Screen1_Label9;
lv_obj_t *ui_Screen1_Label10;
lv_obj_t *ui_Screen1_Label11;
lv_obj_t *ui_lbEngineRPM;
lv_obj_t *ui_lbAltVolt;
lv_obj_t *ui_Screen1_Label12;
lv_obj_t *ui_Screen1_Label13;
lv_obj_t *ui_Screen1_Label14;
lv_obj_t *ui_Screen1_Label15;

//SCREEN: ui_ScreenSplash
void ui_ScreenSplash_screen_init(void);
lv_obj_t *ui_ScreenSplash;
lv_obj_t *ui_ScreenSplash_Image1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);

lv_timer_set_repeat_count(lv_timer_create(endSplash, 8000, NULL), 1);
ui_ScreenSplash_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenSplash);
}

void endSplash(lv_timer_t * timer)
{
    LV_LOG("splash ended");
    ui_Screen1_screen_init();
    lv_disp_load_scr( ui_Screen1);
    lv_obj_del( ui_ScreenSplash);
}