// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: nmea2000_wind_mfd

#ifndef _NMEA2000_WIND_MFD_UI_H
#define _NMEA2000_WIND_MFD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Screen1_Image1;
extern lv_obj_t *ui_Screen1_Image2;
extern lv_obj_t *ui_lbWaterTemp;
extern lv_obj_t *ui_Screen1_Label6;
extern lv_obj_t *ui_Screen1_Label7;
extern lv_obj_t *ui_lbFuelFlow;
extern lv_obj_t *ui_lbFuelBurned;
extern lv_obj_t *ui_Screen1_Label8;
extern lv_obj_t *ui_Screen1_Label9;
extern lv_obj_t *ui_Screen1_Label10;
extern lv_obj_t *ui_Screen1_Label11;
extern lv_obj_t *ui_lbEngineRPM;
extern lv_obj_t *ui_lbAltVolt;
extern lv_obj_t *ui_Screen1_LabelRPM;
extern lv_obj_t *ui_Screen1_LabelVolt_Units;
extern lv_obj_t *ui_Screen1_LabelVoltage;
extern lv_obj_t *ui_Screen1_Label15;

//SCREEN: ui_ScreenSplash
void ui_Screen1_screenSplash_init(void);
extern lv_obj_t *ui_ScreenSplash;
extern lv_obj_t *ui_ScreenSplash_Image1;

// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( chrislogo);
LV_IMG_DECLARE( chrislogo_small);
LV_IMG_DECLARE( BelleIsle);

// UI INIT
void ui_init(void);
void endSplash(lv_timer_t * timer);
void scootImage(lv_timer_t * timer);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
