// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: nmea2000_wind_mfd

#include "ui.h"

void ui_Screen1_screen_init(void)
{

ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Screen1_Image1 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Screen1_Image1, &chrislogo_small); 
lv_obj_set_width( ui_Screen1_Image1, 292);  /// 1
lv_obj_set_height( ui_Screen1_Image1, 50);   /// 1
lv_obj_set_x( ui_Screen1_Image1, 15 );
lv_obj_set_y( ui_Screen1_Image1, 15 );
lv_obj_add_flag( ui_Screen1_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Screen1_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


//shitty animation code
lv_timer_set_repeat_count(lv_timer_create(scootImage, 800, NULL), 900);

//the big map image
ui_Screen1_Image2 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Screen1_Image2, &BelleIsle);
//lv_img_set_zoom(ui_Screen1_Image2, 512);
lv_obj_set_width( ui_Screen1_Image2, 415);  /// 1
lv_obj_set_height( ui_Screen1_Image2, 415);   /// 1
lv_obj_set_x( ui_Screen1_Image2, 0 );
lv_obj_set_y( ui_Screen1_Image2, 65 );
lv_obj_add_flag( ui_Screen1_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Screen1_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
//lv_img_set_size_mode(ui_Screen1_Image2, LV_IMG_SIZE_MODE_REAL); //this flag only works on lvgl 8, need to checkt he function in lvgl code to figure out what args are valid
//lv_image_set_pivot(ui_Screen1_Image2,16,202);
//lv_image_set_rotation(ui_Screen1_Image2,2700);

ui_lbOilPRessure_value = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbOilPRessure_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbOilPRessure_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbOilPRessure_value, -78 );
lv_obj_set_y( ui_lbOilPRessure_value, -154 );
lv_obj_set_align( ui_lbOilPRessure_value, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lbOilPRessure_value,"21.5");
lv_obj_set_style_text_align(ui_lbOilPRessure_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lbOilPRessure_value, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbOilPRessure_value, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelpsiUnits = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelpsiUnits, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelpsiUnits, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelpsiUnits, 334 );
lv_obj_set_y( ui_Screen1_LabelpsiUnits, -140 );
lv_obj_set_align( ui_Screen1_LabelpsiUnits, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelpsiUnits,"psi");
lv_obj_set_style_text_align(ui_Screen1_LabelpsiUnits, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelpsiUnits, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelOilPressure = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelOilPressure, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelOilPressure, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelOilPressure, 280 );
lv_obj_set_y( ui_Screen1_LabelOilPressure, -196 );
lv_obj_set_align( ui_Screen1_LabelOilPressure, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelOilPressure,"Oil Pressure");
lv_obj_set_style_text_color(ui_Screen1_LabelOilPressure, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_LabelOilPressure, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelOilPressure, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

//FUEL FLOW DATA LABEL
ui_lbFuelFlow = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbFuelFlow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbFuelFlow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbFuelFlow, -235 );
lv_obj_set_y( ui_lbFuelFlow, 198 );
lv_obj_set_align( ui_lbFuelFlow, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lbFuelFlow,"8.8");
lv_obj_set_style_text_align(ui_lbFuelFlow, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lbFuelFlow, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbFuelFlow, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

//FUEL BURN DATA LABEL
ui_lbFuelBurned_Value = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbFuelBurned_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbFuelBurned_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbFuelBurned_Value, -74 );
lv_obj_set_y( ui_lbFuelBurned_Value, 198 );
lv_obj_set_align( ui_lbFuelBurned_Value, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lbFuelBurned_Value,"12.8");
lv_obj_set_style_text_align(ui_lbFuelBurned_Value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lbFuelBurned_Value, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbFuelBurned_Value, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelFuelFlow = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelFuelFlow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelFuelFlow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelFuelFlow, 141 );
lv_obj_set_y( ui_Screen1_LabelFuelFlow, 152 );
lv_obj_set_align( ui_Screen1_LabelFuelFlow, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelFuelFlow,"Fuel Flow");
lv_obj_set_style_text_color(ui_Screen1_LabelFuelFlow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_LabelFuelFlow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelFuelFlow, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label9 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_Label9, 285 );
lv_obj_set_y( ui_Screen1_Label9, 152 );
lv_obj_set_align( ui_Screen1_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_Label9,"Fuel Burn");
lv_obj_set_style_text_color(ui_Screen1_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label9, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelGPH = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelGPH, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelGPH, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelGPH, 199 );
lv_obj_set_y( ui_Screen1_LabelGPH, 207 );
lv_obj_set_align( ui_Screen1_LabelGPH, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelGPH,"GPH");
lv_obj_set_style_text_align(ui_Screen1_LabelGPH, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelGPH, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelGallons = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelGallons, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelGallons, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelGallons, 365 );
lv_obj_set_y( ui_Screen1_LabelGallons, 207 );
lv_obj_set_align( ui_Screen1_LabelGallons, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelGallons,"Gallons");
lv_obj_set_style_text_color(ui_Screen1_LabelGallons, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_LabelGallons, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelGallons, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbEngineRPM_value = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbEngineRPM_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbEngineRPM_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbEngineRPM_value, -103 );
lv_obj_set_y( ui_lbEngineRPM_value, 83 );
lv_obj_set_align( ui_lbEngineRPM_value, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lbEngineRPM_value,"12356");
lv_obj_set_style_text_align(ui_lbEngineRPM_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lbEngineRPM_value, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbEngineRPM_value, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbAltVolt = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbAltVolt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbAltVolt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbAltVolt, -77 );
lv_obj_set_y( ui_lbAltVolt, -28 );
lv_obj_set_align( ui_lbAltVolt, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lbAltVolt,"12.8");
lv_obj_set_style_text_align(ui_lbAltVolt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lbAltVolt, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbAltVolt, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelRPM = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelRPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelRPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelRPM, 323 );
lv_obj_set_y( ui_Screen1_LabelRPM, 91 );
lv_obj_set_align( ui_Screen1_LabelRPM, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelRPM,"RPM");
lv_obj_set_style_text_color(ui_Screen1_LabelRPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_LabelRPM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelRPM, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelVolt_Units = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelVolt_Units, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelVolt_Units, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelVolt_Units, 335 );
lv_obj_set_y( ui_Screen1_LabelVolt_Units, -21 );
lv_obj_set_align( ui_Screen1_LabelVolt_Units, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelVolt_Units,"V");
lv_obj_set_style_text_color(ui_Screen1_LabelVolt_Units, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_LabelVolt_Units, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelVolt_Units, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelVoltage = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelVoltage, 273 );
lv_obj_set_y( ui_Screen1_LabelVoltage, -74 );
lv_obj_set_align( ui_Screen1_LabelVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelVoltage,"Alternator Voltage");
lv_obj_set_style_text_color(ui_Screen1_LabelVoltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_LabelVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelVoltage, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelEngineSpeed = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelEngineSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelEngineSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelEngineSpeed, 280 );
lv_obj_set_y( ui_Screen1_LabelEngineSpeed, 43 );
lv_obj_set_align( ui_Screen1_LabelEngineSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelEngineSpeed,"Engine Speed");
lv_obj_set_style_text_color(ui_Screen1_LabelEngineSpeed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_LabelEngineSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelEngineSpeed, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);


}
int xcounterthing = 1;
//actual shitty animation code
void scootImage(lv_timer_t * timer)
{
  xcounterthing--;
  lv_obj_invalidate(ui_Screen1_Image2);
  LV_LOG("scooting image");
  lv_image_set_src(ui_Screen1_Image2, &BelleIsle);
  //lv_img_set_zoom(ui_Screen1_Image2, 512);
  lv_obj_set_width( ui_Screen1_Image2, 415 + (xcounterthing * -1));  /// 1
  lv_obj_set_height( ui_Screen1_Image2, 415);   /// 1
  lv_obj_set_x( ui_Screen1_Image2, xcounterthing );
  lv_obj_set_y( ui_Screen1_Image2, 65 );
  lv_obj_add_flag( ui_Screen1_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
  lv_obj_remove_flag( ui_Screen1_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
  //lv_img_set_size_mode(ui_Screen1_Image2, LV_IMG_SIZE_MODE_REAL);
  //lv_obj_set_x( ui_Screen1_Image2, xcounterthing );
}