// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: nmea2000_wind_mfd

#include "ui.h"

void ui_Screen1_screen_init(void)
{

ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Screen1_Image1 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Screen1_Image1, &chrislogo_small); 
lv_obj_set_width( ui_Screen1_Image1, 292);  /// 1
lv_obj_set_height( ui_Screen1_Image1, 50);   /// 1
lv_obj_set_x( ui_Screen1_Image1, 15 );
lv_obj_set_y( ui_Screen1_Image1, 15 );
lv_obj_add_flag( ui_Screen1_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Screen1_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


//shitty animation code
lv_timer_set_repeat_count(lv_timer_create(scootImage, 2000, NULL), 100);

//the big map image
ui_Screen1_Image2 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Screen1_Image2, &BelleIsle);
//lv_img_set_zoom(ui_Screen1_Image2, 512);
lv_obj_set_width( ui_Screen1_Image2, 415);  /// 1
lv_obj_set_height( ui_Screen1_Image2, 415);   /// 1
lv_obj_set_x( ui_Screen1_Image2, 0 );
lv_obj_set_y( ui_Screen1_Image2, 65 );
lv_obj_add_flag( ui_Screen1_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Screen1_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
//lv_img_set_size_mode(ui_Screen1_Image2, LV_IMG_SIZE_MODE_REAL); //this flag only works on lvgl 8, need to checkt he function in lvgl code to figure out what args are valid
//lv_image_set_pivot(ui_Screen1_Image2,16,202);
//lv_image_set_rotation(ui_Screen1_Image2,2700);

ui_lbWaterTemp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbWaterTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbWaterTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbWaterTemp, -78 );
lv_obj_set_y( ui_lbWaterTemp, -154 );
lv_obj_set_align( ui_lbWaterTemp, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lbWaterTemp,"21.5");
lv_obj_set_style_text_align(ui_lbWaterTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lbWaterTemp, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbWaterTemp, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_Label6, 333 );
lv_obj_set_y( ui_Screen1_Label6, -172 );
lv_obj_set_align( ui_Screen1_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_Label6,"o");
lv_obj_set_style_text_align(ui_Screen1_Label6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label6, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_Label7, 251 );
lv_obj_set_y( ui_Screen1_Label7, -196 );
lv_obj_set_align( ui_Screen1_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_Label7,"Water Temperature");
lv_obj_set_style_text_color(ui_Screen1_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label7, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

//FUEL FLOW DATA LABEL
ui_lbFuelFlow = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbFuelFlow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbFuelFlow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbFuelFlow, -235 );
lv_obj_set_y( ui_lbFuelFlow, 195 );
lv_obj_set_align( ui_lbFuelFlow, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lbFuelFlow,"8.8");
lv_obj_set_style_text_align(ui_lbFuelFlow, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lbFuelFlow, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbFuelFlow, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

//FUEL BURN DATA LABEL
ui_lbFuelBurned = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbFuelBurned, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbFuelBurned, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbFuelBurned, -74 );
lv_obj_set_y( ui_lbFuelBurned, 198 );
lv_obj_set_align( ui_lbFuelBurned, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lbFuelBurned,"12.8");
lv_obj_set_style_text_align(ui_lbFuelBurned, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lbFuelBurned, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbFuelBurned, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_Label8, 141 );
lv_obj_set_y( ui_Screen1_Label8, 152 );
lv_obj_set_align( ui_Screen1_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_Label8,"Fuel Flow");
lv_obj_set_style_text_color(ui_Screen1_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label8, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label9 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_Label9, 285 );
lv_obj_set_y( ui_Screen1_Label9, 152 );
lv_obj_set_align( ui_Screen1_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_Label9,"Fuel Burn");
lv_obj_set_style_text_color(ui_Screen1_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label9, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label10 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_Label10, 199 );
lv_obj_set_y( ui_Screen1_Label10, 207 );
lv_obj_set_align( ui_Screen1_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_Label10,"GPH");
lv_obj_set_style_text_align(ui_Screen1_Label10, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label10, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label11 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_Label11, 365 );
lv_obj_set_y( ui_Screen1_Label11, 207 );
lv_obj_set_align( ui_Screen1_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_Label11,"Gallons");
lv_obj_set_style_text_color(ui_Screen1_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label11, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbEngineRPM = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbEngineRPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbEngineRPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbEngineRPM, -103 );
lv_obj_set_y( ui_lbEngineRPM, 83 );
lv_obj_set_align( ui_lbEngineRPM, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lbEngineRPM,"12356");
lv_obj_set_style_text_align(ui_lbEngineRPM, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lbEngineRPM, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbEngineRPM, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbAltVolt = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbAltVolt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbAltVolt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbAltVolt, -77 );
lv_obj_set_y( ui_lbAltVolt, -28 );
lv_obj_set_align( ui_lbAltVolt, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lbAltVolt,"12.8");
lv_obj_set_style_text_align(ui_lbAltVolt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lbAltVolt, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbAltVolt, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelRPM = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelRPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelRPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelRPM, 323 );
lv_obj_set_y( ui_Screen1_LabelRPM, 91 );
lv_obj_set_align( ui_Screen1_LabelRPM, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelRPM,"RPM");
lv_obj_set_style_text_color(ui_Screen1_LabelRPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_LabelRPM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelRPM, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelVolt_Units = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelVolt_Units, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelVolt_Units, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelVolt_Units, 335 );
lv_obj_set_y( ui_Screen1_LabelVolt_Units, -21 );
lv_obj_set_align( ui_Screen1_LabelVolt_Units, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelVolt_Units,"V");
lv_obj_set_style_text_color(ui_Screen1_LabelVolt_Units, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_LabelVolt_Units, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelVolt_Units, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_LabelVoltage = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_LabelVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_LabelVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_LabelVoltage, 273 );
lv_obj_set_y( ui_Screen1_LabelVoltage, -74 );
lv_obj_set_align( ui_Screen1_LabelVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_LabelVoltage,"Alternator Voltage");
lv_obj_set_style_text_color(ui_Screen1_LabelVoltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_LabelVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_LabelVoltage, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label15 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_Label15, 280 );
lv_obj_set_y( ui_Screen1_Label15, 43 );
lv_obj_set_align( ui_Screen1_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_Label15,"Engine Speed");
lv_obj_set_style_text_color(ui_Screen1_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1_Label15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label15, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);


}
int xcounterthing = 1;
//actual shitty animation code
void scootImage(lv_timer_t * timer)
{
  xcounterthing--;
  lv_obj_invalidate(ui_Screen1_Image2);
  LV_LOG("scooting image");
  lv_image_set_src(ui_Screen1_Image2, &BelleIsle);
  //lv_img_set_zoom(ui_Screen1_Image2, 512);
  lv_obj_set_width( ui_Screen1_Image2, 415 + (xcounterthing * -1));  /// 1
  lv_obj_set_height( ui_Screen1_Image2, 415);   /// 1
  lv_obj_set_x( ui_Screen1_Image2, xcounterthing );
  lv_obj_set_y( ui_Screen1_Image2, 65 );
  lv_obj_add_flag( ui_Screen1_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
  lv_obj_remove_flag( ui_Screen1_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
  //lv_img_set_size_mode(ui_Screen1_Image2, LV_IMG_SIZE_MODE_REAL);
  //lv_obj_set_x( ui_Screen1_Image2, xcounterthing );
}