// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: nmea2000_wind_mfd

#include "ui.h"

void ui_ScreenSplash_screen_init(void)
{

ui_ScreenSplash = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenSplash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScreenSplash_Image1 = lv_image_create(ui_ScreenSplash);
lv_image_set_src(ui_ScreenSplash_Image1, &chrislogo); //ui_img_wind_png
lv_obj_set_width( ui_ScreenSplash_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenSplash_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenSplash_Image1, 50 );
lv_obj_set_y( ui_ScreenSplash_Image1, 180 );
lv_obj_add_flag( ui_ScreenSplash_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_ScreenSplash_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
